### PR TITLE
Fixes #11 - Add device id in response

### LINKED ISSUE #11: Wrong ID Returned When executing the OneSignal.viewDevices Method
We're attempting to get the playerIds using the specification defined for the RESTful endpoint at https://onesignal.com/api/v1/players?app_id={appId}&limit=300&offset=0

When running with curl, the results come back as expected, for example:
{"id":"a3xxxxx-a80f-4xxd-98xx-c5xxbe7xxxxx","identifier":null,"session_count":2,"language":"en","timezone":-25200,"game_version":"2.8.1","device_os":"9.3","device_type":0,"device_model":"x86_64","ad_id":"7ExxxxxA75-7Axx-4xxD-9F27-5BExxxxxxxxxx","tags":{},"last_active":1472105955,"playtime":0,"amount_spent":0.0,"created_at":1472105504,"invalid_identifier":true,"badge_count":0,"sdk":"011103","test_type":null}

However, when invoking the CurrencyFair method OneSignal.viewDevices(restkey, appId, limit, offset), calling with the same parameters, the "identifier" returned is the player's ios or android token. There is no place on the list of ViewDevicesResponse objects that contains the correct userId/playerId.

### PR DESCRIPTION
**Pull request by ericcwcw**
Performed end-to-end testing by packaging it into jar locally and calling `OneSignal.viewDevices()`

### CODE REVIEW

**Review by zol777 — APPROVED** [review]

**Review by lokkyC — APPROVED** [review]

File: src/main/java/com/currencyfair/onesignal/model/player/ViewDeviceResponse.java [hunk 1]
```diff
@@ -22,13 +22,25 @@
  * Response class for {@link com.currencyfair.onesignal.OneSignal#viewDevice(String, String, String)} request.
  */
 public class ViewDeviceResponse extends Device {
+    /**
+     * The device's OneSignal ID
+     */
+    private String id;
```
Comment (lokkyC) [inline src/main/java/com/currencyfair/onesignal/model/player/ViewDeviceResponse.java:28]: Not sure do id need `@JsonProperty` as well ?

Comment (ericcwcw) [reply src/main/java/com/currencyfair/onesignal/model/player/ViewDeviceResponse.java:28]: I guess it is optional if the property name is the same as that of variable, for example https://github.com/CurrencyFair/OneSignal-Java-SDK/blob/2393a98adae4cc014e7e7033d00473b9ade16940/src/main/java/com/currencyfair/onesignal/model/player/ViewDevicesResponse.java#L37
